- .github/workflows/deploy.yml
- .github/workflows/github-pages.yml
- .github/workflows/test-pull-request.yml
Upgrading all workflows
- `actions/setup-node@v4`, (from v3), node version to `lts/iron`
- `borales/actions-yarn@v4` (from v3)
- `actions/checkout@v4` (from v3)
- `actions/cache@v4` (from v2)
- `actions/github-script@v7` (from v6)
Stop using old things.
Via this PR.
> modernize workflows to node20 and latest versions

- .github/workflows/github-pages.yml
workflow alignment with 
https://github.com/AdobeDocs/VIPMP/blob/d1580f29935505ef81898f1096a4549021983c7d/.github/workflows/test-pull-request.yml#L61-L78
and
https://github.com/AdobeDocs/VIPMP/blob/d1580f29935505ef81898f1096a4549021983c7d/.github/workflows/deploy.yml#L81-L99
> align yarn in pages with deploy and test

- gatsby-config.js
> updating path prefix

- gatsby-config.js
> updated path prefix 

- src/pages/index.md
> Minor fixes. 

- gatsby-config.js
> Topic structure from API guide.

- gatsby-config.js
- src/pages/docs/authentication/health_check.md
> Corrections to global nav. 

- gatsby-config.js
- src/pages/docs/reseller_account/create_reseller_account.md
- src/pages/docs/reseller_account/get_reseller_account.md
- src/pages/docs/reseller_account/index.md
- src/pages/docs/reseller_account/update_reseller_account.md
> Updates to reseller account documentation

- .github/workflows/deploy.yml
moving back to official static-website-deploy job.
> use AdobeDocs/static-website-deploy

- .github/workflows/deploy.yml
- .github/workflows/github-pages.yml
- .github/workflows/test-pull-request.yml
> Stabilize workflows

- yarn.lock
the build logs keep asking for this.
> npx update-browserlist-db@latest

- gatsby-config.js
- src/pages/docs/authentication/overview.md
- src/pages/docs/reseller_account/create_reseller_account.md
- src/pages/docs/reseller_account/get_reseller_account.md
- src/pages/docs/reseller_account/index.md
- src/pages/docs/reseller_account/update_reseller_account.md
- src/pages/docs/reseller_change/commit_transfer.md
- src/pages/docs/reseller_change/get_transfer.md
- src/pages/docs/reseller_change/preview_transfer.md
- src/pages/docs/reseller_change/use_cases.md
> Fixes for MD file

- gatsby-config.js
- src/pages/docs/customer_account/linked_membership.md
> Updates to linked memberships

- gatsby-config.js
- src/pages/docs/customer_account/linked_membership.md
- src/pages/technical-assets/index.md
> Updates based on feedback

- gatsby-config.js
- src/pages/sandbox/introduction/api_collection.md
- src/pages/sandbox/sandbox_portal/index.md
> Adding sandbox files to left-nav

- gatsby-config.js
- src/pages/sandbox/sandbox_portal/3yc_management/index.md
> Changes to Sandbox topics structure

- gatsby-config.js
> Fixes to left-nav

- gatsby-config.js
> Trial and error with left-nav

- gatsby-config.js
> Fix to Sandbox navigation.

- gatsby-config.js
> Added more topics to the tree

- gatsby-config.js
> Folder restructuring - Version 2

- gatsby-config.js
- src/pages/docs/index.md
- src/pages/index.md
> Bacground image change and broken link fixes.

- src/pages/index.md
> Home page changes.

- src/pages/docs/index.md
- src/pages/docs/release_notes/index.md
- src/pages/docs/release_notes/upcoming_releases.md
> Updates to release notes

- src/pages/docs/customer_account/three_year_commit.md
- src/pages/docs/release_notes/index.md
> Broken links and RN

- gatsby-config.js
- src/pages/docs/references/resources.md
- src/pages/docs/release_notes/upcoming_releases.md
> Incorporating review comments

- gatsby-config.js
- src/pages/docs/subscription_management/create_subscription.md
- src/pages/docs/subscription_management/get_details.md
- src/pages/docs/subscription_management/get_details_for_customers.md
> Added missing files

- src/pages/docs/support.md
> Updated support information

- src/pages/docs/lga/convert.md
- src/pages/docs/lga/migrate.md
Another pass at the JSON blocks.
Easier to read/use if the formatting is clean.
> tweak json blocks

- src/pages/docs/lga/migrate.md
> Fix in LGA doc based on feedback.

- src/pages/docs/recommendations/apis.md
> Tracker ID info for recommendations

- src/pages/docs/recommendations/apis.md
- src/pages/docs/recommendations/error_codes.md
- src/pages/docs/recommendations/index.md
> Incorporated feedback received.

- gatsby-config.js
- src/pages/docs/resources/index.md
- src/pages/docs/resources/processes.md
> Changes to left-side nav

- gatsby-config.js
> Modifications to left-side navigation

- src/pages/docs/recommendations/apis.md
> Correcting JSON indentation

- gatsby-config.js
- src/pages/sandbox/sandbox_portal/operations.md
> Updates to sandbox navigation

- src/pages/docs/recommendations/apis.md
> Change to GET Subscription API doc

- src/pages/docs/recommendations/apis.md
> API URL change

- src/pages/docs/customer_account/three_year_commit.md
- src/pages/docs/flex_promo/apis.md
> Incorporating feedback to 3YC and flex promo

- gatsby-config.js
- src/pages/docs/manage_pricing/index.md
> Price List Changes

- src/pages/docs/references/error_handling.md
- src/pages/docs/release_notes/index.md
- src/pages/docs/release_notes/upcoming_releases.md
> Changes to error codes and release notes.

- src/pages/docs/references/error_handling.md
> Updates to flex promo error codes

- src/pages/docs/flex_discounts/apis.md
- src/pages/docs/flex_discounts/index.md
- src/pages/docs/manage_pricing/index.md
> Changes to flex promo and price list

- src/pages/docs/manage_pricing/index.md
> Changes to Pricelist documentation

- src/pages/docs/customer_account/three_year_commit.md
- src/pages/docs/lga/migrate.md
- src/pages/docs/subscription_management/create_subscription.md
> Incorporate review comments

- src/pages/docs/references/error_handling.md
- src/pages/docs/subscription_management/get_details_for_customers.md
> changes to Error codes and get customers

- src/pages/docs/order_management/order_scenarios.md
- src/pages/docs/release_notes/index.md
> Changes to release notes and order scenarios based on the feedback

- src/pages/docs/customer_account/get_customer_list.md
> Minor change to param name.

- src/pages/docs/order_management/order_scenarios.md
- src/pages/docs/release_notes/index.md
> Incorprated feedback from legal.

- src/pages/docs/order_management/order_scenarios.md
> Fix to content issues

- src/pages/docs/customer_account/update_customer_account.md
> Updates based on feedback from partners

- src/pages/docs/customer_account/get_licenses.md
- src/pages/docs/release_notes/upcoming_releases.md
> Updates to get licenses

- src/pages/docs/mid_term/apis.md
- src/pages/docs/mid_term/error_codes.md
- src/pages/docs/mid_term/index.md
- src/pages/docs/release_notes/upcoming_releases.md
> Updates based on code changes.
